### ISSUE TITLE
Allow use to add ingredients directly from the meal show page

### ISSUE THREAD

**Issue by emgord** [emgord/MyPlateMealPlanner#8]
Instead of navigating to a new page to add an ingredient, allow the user to add more ingredients directly from the meal detail page.

**Comment by trowbrsa** [comment]
I can help with this!

**Comment by emgord** [comment]
Hooray! Thanks for taking this on.

**Comment by trowbrsa** [comment]
Hey @emgord, I've started on this and have a few questions. First, I want to confirm that I am adding the ability to add ingredients on the same page as the meals#new page. I've added the ingredients partial, so that you can add 1 single ingredient to a meal. See the attached image for reference. 
![screen shot 2015-12-29 at 3 26 11 pm](https://cloud.githubusercontent.com/assets/6278193/12044075/8b2caa86-ae40-11e5-87f1-b9d88f7ce097.png)
However, some other logic I am thinking about that I'd like your input on: 

1.) Do you want the ability to add multiple ingredients on the page? Should I have it render the 'add ingredient' view 3 times per meal for example?

2.) right now, you can either create a meal or add an ingredient, since there can be one action per page. Do you have any solutions for how to trigger multiple actions per page, so that both the meal and the ingredients get submitted? 

Thanks!

**Comment by emgord** [comment]
Thanks for checking in! I like what you've done so far. I was actually envisioning that users would be able to add an ingredient directly from the bottom of the meals#show page (http://myplatemealplan.herokuapp.com/meals/4), so instead of going to a new page and clicking back and forth if they want to add lots of ingredients, the page would allow the user keep adding ingredients from the same page instead. I tried this when I initially created it, and I couldn't figure out how to get it to add ingredients when the page was actually connected with the meals controller, so I was thinking that it might require changing the routes so that page is actually connected to the ingredients controller somehow? Perhaps if we switched that page to the ingredients#index route, which right now nested with meals in the meals_ingredients path.
I think if you can get it to allow you to add ingredients at the same time as creating a meal that would also be lovely, but it sounds like right now you can't submit both at once so that may not be practical.

**Comment by trowbrsa** [comment]
Great, thanks for the feedback! I'll see what I can do!
